fix: fix the pr title check

diff --git a/pr-title-check/action.yml b/pr-title-check/action.yml
--- a/pr-title-check/action.yml
+++ b/pr-title-check/action.yml
@@ -2,12 +2,16 @@ name: "PR Title Check"
 description: "Check if the pull request title follows the conventional commit format."
 
 runs:
-  using: composite
+  using: "composite"
   steps:
-    - run: |
-      if [[ ! "$(echo '${{ github.event.pull_request.title }}' | grep -E '^(fix|feat|tech|docs|bump|style|refactor|chore|perf|test|revert|breaking)(\([^)]+\))?:')" ]]; then
-      echo "Error:
-        Pull request title must start with one of the following keywords: fix, feat, tech, docs, bump, style, refactor, chore, perf, test, breaking or revert. Optionally, it can include a scope in parentheses followed by a colon (e.g., 'feat(scope):')."
-      exit 1
-      fi
-    shell: bash
+    - name: Check PR title format
+      shell: bash
+      run: |
+        title="${{ github.event.pull_request.title }}"
+        if ! echo "$title" | grep -Eq '^(fix|feat|tech|docs|bump|style|refactor|chore|perf|test|revert|breaking)(\([^)]+\))?:'; then
+          echo "❌ Error:
+          Pull request title must start with one of the following keywords:
+          fix, feat, tech, docs, bump, style, refactor, chore, perf, test, breaking or revert.
+          Optionally, it can include a scope in parentheses followed by a colon (e.g., 'feat(scope):')."
+          exit 1
+        fi
